#!/bin/env bash

if [ "$1" == 'reload' ]; then
    exec "$SNAP/bin/kill" -1 $(cat $SNAP_DATA/datadir/i2pd.pid)
elif [ "$1" == 'gaceful' ]; then
    exec "$SNAP/bin/kill" -2 $(cat $SNAP_DATA/datadir/i2pd.pid)
else
    if [ ! -d "$SNAP_DATA/datadir" ]; then
        mkdir $SNAP_DATA/datadir/
        cp -R $SNAP/certificates $SNAP_DATA/datadir/
        cp -R $SNAP/i2pd.conf $SNAP_DATA/datadir/
    fi

    exec "$SNAP/bin/i2pd" --datadir=$SNAP_DATA/datadir/
fi