#!/bin/sh

if [ ! -d "$SNAP_DATA/datadir" ]; then
  mkdir $SNAP_DATA/datadir/
  cp -R $SNAP/certificates $SNAP_DATA/datadir/
  cp -R $SNAP/i2pd.conf $SNAP_DATA/datadir/
fi

exec "$SNAP/bin/i2pd" --datadir=$SNAP_DATA/datadir/
