#!/bin/sh

if [ ! -d "$SNAP_USER_DATA/.i2pd" ]; then
  mkdir $SNAP_USER_DATA/.i2pd/
  cp -R $SNAP/certificates $SNAP_USER_DATA/.i2pd/
  cp -R $SNAP/i2pd.conf $SNAP_USER_DATA/.i2pd/
fi

exec "$SNAP/bin/i2pd" "$@"
