name: i2pd
summary: Distributed anonymous networking framework
description: |
    i2pd (I2P Daemon) is a full-featured C++ implementation of I2P client.
    I2P (Invisible Internet Protocol) is a universal anonymous network layer.
    All communications over I2P are anonymous and end-to-end encrypted,
    participants don't reveal their real IP addresses.
version: 2.52.0

website: https://i2pd.website/
source-code: https://github.com/PurpleI2P/i2pd-snap
issues: https://github.com/PurpleI2P/i2pd/issues
license: BSD-3-Clause

icon: i2pd.png
base: core22
grade: stable
confinement: strict

apps:
  daemon:
    command: i2pd-wrapper
    daemon: simple
    plugs:
    - network
    - network-bind

  graceful-shutdown:
    command: i2pd-wrapper graceful

  reload-tunnels-conf:
    command: i2pd-wrapper reload

parts:
  i2pd:
    plugin: make
    source: https://github.com/PurpleI2P/i2pd.git
    source-type: git
    source-tag: 2.52.0
    #source-commit: 6ca6591c4365d62873eeac6328e5b1932862a614
    build-packages:
    - build-essential
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libminiupnpc-dev
    - libssl-dev
    - zlib1g-dev
    override-build: |
      make DEBUG=no USE_UPNP=yes -j`nproc`
      mkdir $SNAPCRAFT_PART_INSTALL/appdata $SNAPCRAFT_PART_INSTALL/bin
      cp i2pd $SNAPCRAFT_PART_INSTALL/bin/
      cp -r contrib/i2pd.conf contrib/tunnels.conf contrib/certificates $SNAPCRAFT_PART_INSTALL/appdata/
    stage-packages:
    - libboost-date-time1.74.0
    - libboost-filesystem1.74.0
    - libboost-program-options1.74.0
    - libboost-system1.74.0
    - libminiupnpc17
    - libssl3
    - zlib1g
  wrapper:
    plugin: dump
    source: snap/local/
    stage:
    - i2pd-wrapper
