name: i2pd
summary: Distributed anonymous networking framework
description: |
    i2pd (I2P Daemon) is a full-featured C++ implementation of I2P client.
    I2P (Invisible Internet Protocol) is a universal anonymous network layer.
    All communications over I2P are anonymous and end-to-end encrypted,
    participants don't reveal their real IP addresses.
version: 2.45.1
icon: snap/gui/i2pd.png
base: core22
grade: stable
type: app
confinement: strict

apps:
  daemon:
    command: i2pd-wrapper
    daemon: simple
    plugs: [network,network-bind]
  graceful-shutdown:
    command: kill -2 `cat $SNAP_DATA/datadir/i2pd.pid`
  reload-tunnels-conf:
    command: kill -1 `cat $SNAP_DATA/datadir/i2pd.pid`

parts:
  i2pd:
    source: https://github.com/PurpleI2P/i2pd.git
    source-type: git
    source-tag: 2.45.1
    plugin: make
    make-parameters:
      - USE_UPNP=yes
      - DEBUG=no
    build-packages:
      - build-essential
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libminiupnpc-dev
      - libssl-dev
      - zlib1g-dev
    stage-packages:
      - libboost-date-time
      - libboost-filesystem
      - libboost-program-options
      - libboost-system
      - libminiupnpc17
      - libssl1.1
      - zlib1g
    organize:
      i2pd: bin/
      contrib/*: .
  wrapper:
    plugin: dump
    source: snap/local/
    stage: [i2pd-wrapper]
